### ISSUE TITLE
Out of range value for column 'retail_price'

### ISSUE THREAD

**Issue by lexar** [billy1380/JavaEPFImporter#10]
I see the error 'Out of range value for column 'retail_price' while importing. I think it's because DECIMAL(9,3) has not enough digits for some currencies. I think the solution would be to increase the digits (i.e. DECIMAL(16,3).
I see there is a DECIMAL definition in smalldata/application_price. Should I change it there?
Or should I do that in the database? 

Thanks in advance!

**Comment by billy1380** [comment]
smalldata is just a cut down sample of data (which is very old now) from when I was writing this importer. If you can get a fresh version from apple it should have the correct column definitions, which means that the import of that file will work for its definitions.

Having said that, the included data should import with no issues, the DECIMAL(9,3) comes from the epf files so not sure why that would be the cause.

Since, as far as I can remember, the small data import is quite fast, it might be worth dropping the table and trying to import it again.

**Comment by lexar** [comment]
I see. I had this error with the latest full file from Apple, the definition is in there:
DECIMAL(9,3)
So I guess I have to go to Apple with that problem.
I wrongly assumed the small data folder contains some hints about the expected data, I understand now it's just for testing.
Thanks again!
